querly.gemspec
Problem 1
----
First, I've grabbed an error of `racc` when run `rake racc`
```sh
$ bundle exec rake racc
racc -v -o lib/querly/pattern/parser.rb lib/querly/pattern/parser.y
/home/pocke/.gem/ruby/2.3.0/gems/bundler-1.12.5/lib/bundler/rubygems_integration.rb:322:in `block in replace_gem': racc is not part of the bundle. Add it to Gemfile. (Gem::LoadError)
from /home/pocke/.gem/ruby/2.3.0/bin/racc:22:in `<main>'
rake aborted!
Command failed with status (1): [racc -v -o lib/querly/pattern/parser.rb li...]
/home/pocke/ghq/github.com/soutaro/querly/Rakefile:15:in `block in <top (required)>'
/home/pocke/.gem/ruby/2.3.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `load'
/home/pocke/.gem/ruby/2.3.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `kernel_load' …
```
=> Fix installation the gem

CHANGELOG.md, README.md, lib/querly.rb, lib/querly/config.rb, lib/querly/rules/sample.rb, rules/sample.yml, sample.yaml
* Allow publishing your rules as Ruby script
* Add `require` command for rules
Example configuration:
```yaml
import:
- require: querly/rules/sample
- require: your_library/querly/rules
```
=> Require Rules from Ruby Script

test/config_test.rb
`test_loading_rules_from_file` test is failed in my environment.
```
$ bundle exec rake
Run options: --seed 62459
...................F.......................................................................................
Finished in 4.031457s, 26.5413 runs/s, 70.9421 assertions/s.
1) Failure:
ConfigTest#test_loading_rules_from_file [/home/pocke/ghq/github.com/soutaro/querly/test/config_test.rb:95]:
--- expected
+++ actual
@@ -1 +1 @@
-["rule1", "rule2", "rule3", "rule4"]
+["rule1", "rule3", "rule4", "rule2"]
107 runs, 286 assertions, 1 failures, 0 errors, 0 skips
```
The order of values returned by `Pathname.glob` depends on system.
> Note that this pattern is not a regexp, it’s closer to a shell glob. See File.fnmatch for the meaning of the flags parameter. Note that case sensitivity …
=> Prevent failure test due to environmental dependence

lib/querly/script_enumerator.rb
For example, `.jb` is a Ruby program, but querly does not analyse `.jb` currently.
This change makes to analyse `.jb` and more ruby files by default.
The extensions and basenames list is referred to RuboCop. https://github.com/pocke/rubocop/blob/2b71ecc7a396ae0364d3801a7b65dc8ca85d26f0/config/default.yml#L11-L56
=> Include more ruby files by default

lib/querly/cli.rb, lib/querly/cli/test.rb, test/cli/test_test.rb
Make `$ querly test` exit with `1` when it finds something wrong.
This allows running `test` in CI to make some sense.
=> Exit 1 on test failure

lib/querly/cli/test.rb, test/cli/test_test.rb
querly.yaml
-------------
```yaml
rules:
- id: foo
pattern:
- "bad()"
before:
- 'good()'
- 'bad()'
after:
- 'good()'
message: 'Do not use bad()'
```
before
----------
```bash
$ querly test
Checking rule id uniqueness...
Checking rule patterns...
foo:	0th *before* example didn't match with any pattern
Tested 1 rules with 3 tests.
0 examples found which should not match, but matched
1 examples found which should match, but didn't
0 examples raised error
```
`0th`
after
------------
```bash
$ querly test
Checking rule id uniqueness...
Checking rule patterns...
foo:	1th *before* example didn't match with any pattern
Tested 1 rules with 3 tests.
0 examples found which should not match, but matched
1 examples found which should match, but didn't
0 examples raised error
```
`1th`
=> Use human readable index for error message

lib/querly.rb, lib/querly/cli/test.rb, querly.gemspec, test/cli/test_test.rb
Ordinal forms looks like more human readable 🤝 
```
Checking rule patterns...
sample.order-group:	1st *before* example didn't match with any pattern
sample.order-group:	2nd *before* example didn't match with any pattern
```
=> Ordinalize example index using ActiveSupport

querly.gemspec
activesupport 5.0.x seems to work well.
=> requires activesuport ~> 5.1.1 is too new

lib/querly/pp/cli.rb
Fix #15 
```
$ querly-pp haml < test.haml
/home/pocke/.gem/ruby/2.4.0/gems/querly-0.5.0/lib/querly/pp/cli.rb:59:in `run_haml': HAML 5.0+ is detected. (RuntimeError)
`querly-pp haml` does not work on HAML 5.0+.
Use `haml -d` instead.
from /home/pocke/.gem/ruby/2.4.0/gems/querly-0.5.0/lib/querly/pp/cli.rb:48:in `run'
from /home/pocke/.gem/ruby/2.4.0/gems/querly-0.5.0/exe/querly-pp:7:in `<top (required)>'
from /home/pocke/.gem/ruby/2.4.0/bin/querly-pp:22:in `load'
from /home/pocke/.gem/ruby/2.4.0/bin/querly-pp:22:in `<main>'
```
=> Display error message in `querly-pp haml` if HAML 5.0+ is used

lib/querly/cli.rb, test/smoke_test.rb
Currently, Querly loads only the paths received by arguments. If I do not pass paths, It will not load anything. This behavior makes me confused.
```
$ querly check
```
I think that as with many other linters (e.g. RuboCop, Reek), Querly loads the current directory by default.
=> Load current dir by default

lib/querly/pp/cli.rb
When we use Querly with HAML5, it guides that `haml -d` should be used instead of querly-pp. However, I think that HAML5 support with querly-pp is necessary for graceful migration.
=> Supports HAML5 for querly-pp

lib/querly/script_enumerator.rb, test/smoke_test.rb
Querly does not raise the exception if receiving a file name that does not exist. However, in this case, I would like to display that the file does not exist.
=> Raise LoadError when receiving a file name that does not exist

lib/querly/pattern/expr.rb, lib/querly/pattern/parser.y, test/pattern_parser_test.rb, test/pattern_test_test.rb
Problem
====
Currently, Any pattern matches `nil`.
Therefore, `_.foo` matches `foo`(without receiver). I think this behaviour is confusing. The pattern should match a send node **with receiver**.
For example:
`querly.yaml`
```yaml
rules:
- id: test
pattern: '_.belongs_to(:symbol:, ..., !index: _, ...)'
message: '`belongs_to` adds an index always in Rails 5. If you do not need it, add `index: false`.'
examples:
- before: 't.belongs_to :user'
after:  't.belongs_to :user, index: false'
- after:  'belongs_to :user'
```
`querly test` for the rule definition is failed.
Because the rule matches `belongs_to :user`.
```bash
$ querly test
warning: parser/current is loading parser/ruby24, which recognizes
warning: 2.4.0-compliant syntax, but you are running 2.4.1.
warning: please see …
```
=> Make Any pattern not to match `nil`

lib/querly/pattern/parser.y, test/pattern_parser_test.rb
Fix parsing failure on `assert` since it is tokenized as `as` + `sert`.
=> Parsing assert

lib/querly/pattern/kind.rb, test/pattern_test_test.rb
Receiver of safe navigation operator should be marked as conditional, but querly does not mark it.
For example:
We have a rule for `find_by`.
```yaml
rules:
- id: com.sideci.find_with_bang
pattern: "find_by(_) [!conditional]"
message: find_by returns a nil if the specified record does not exist. Use find_by! instead.
```
```ruby
User.find_by(email: email)&.full_name
```
The `find_by` is in a conditional. So querly should not warn for the code, but querly warns. Because querly does not treat safe navigation operators as a conditional.
This change will fix this problem.
Note: I can't find any tests for conditional kinds. So I added tests for them.
=> Make `[conditional]` kind aware of safe navigation operator

CHANGELOG.md, lib/querly/preprocessor.rb, lib/querly/script_enumerator.rb, test/preprocessor_test.rb, test/test_helper.rb
To handle input correctly, without deadlocking, pass the path to the input, instead of a pipe.
=> Fix preprocessor

querly.gemspec
This patch allows `querly` gem to be used not only with [`thor`](https://github.com/erikhuda/thor) v0.20.0 but with v0.19.0.
Here is the reason:
1. [`foreman`](https://github.com/ddollar/foreman), a CLI tool most [Heroku](https://heroku.com)-based apps depends on, still uses `thor` v0.19.0.
2. When I try to install the latest `querly` along with `foreman` in the same project, I should use [the extremely older version of `foreman`](https://github.com/ddollar/foreman/releases/tag/v0.64.0) [that can be used with `thor` v0.20.0](https://github.com/ddollar/foreman/blob/v0.64.0/foreman.gemspec#L20). 
3. Though I submitted [a pull request to update `foreman` to switch `thor` to v0.20.0](https://github.com/ddollar/foreman/pull/701), I guess the project author won't merge it soon as far as I see …
=> Loosen the restriction of `thor` version

lib/querly/pattern/expr.rb, test/pattern_test_test.rb
Problem
===
Regexp literal matches all literal patterns.
```bash
$ cat test.rb
/a/
$ querly console .
> find :int:
test.rb:1:0   /a/
1 results
> find :symbol:
test.rb:1:0   /a/
1 results
>
```
The cause
===
When `regexp` node, `test_node` method checks nothing.
https://github.com/soutaro/querly/blob/master/lib/querly/pattern/expr.rb#L127-L131
So it always returns `true`.
Solution
====
Check the type of pattern in the `test_node` method.
Note
===
I added missing test cases for other literal patterns (int, float and
bool), and I moved `test_regexp` under the test cases for literal pattern.
And I tweak the `test_regexp` test.
```
def test_regexp
-   nodes = query_pattern(":regexp:", "[/1/, /#{2}/, 3]")
+   nodes = query_pattern(":regexp:", '[/1/, /#{2}/, 3]')
assert_equal 2, nodes.size
- …
```
=> Fix a bug. Regexp literal matches all literal patterns.

querly.gemspec
﻿I tried to use querly but unfortunately I could not install it due to version conflicts of parser with Rubocop. [Rubocop](https://rubygems.org/gems/rubocop), from version 0.53.0, depends on the parser version 2.5. For example, a version conflict error occurs with the following Gemfile:
```ruby
source "https://rubygems.org"
git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }
gem "querly"
gem "rubocop", "~> 0.53.0"
```
Error:
```bash
$ bundle install
Fetching gem metadata from https://rubygems.org/...............
Resolving dependencies...
Bundler could not find compatible versions for gem "parser":
In snapshot (Gemfile.lock):
parser (= 2.4.0.2)
In Gemfile:
querly was resolved to 0.9.0, which depends on
parser (~> 2.4.0)
rubocop (~> 0.53.0) was resolved to 0.53.0, which …
```
=> Update parser to 2.5

template.yml
Follow up of #39.
I picked up a typical typos using misspell and applied it.
https://github.com/client9/misspell
```console
% misspell -w .
template.yml:31:10: corrected "probablly" to "probably"
```
=> Fix typo intemplate.yml

lib/querly/cli/console.rb
Querly console will highlight matched expression by this change.
I think the highlighting is helpful to check the output.
This pull request also changes the output source code. Currently the source code is a node's. But it will be a line's by this pull request.
For example, the difference makes different outputs in the following case.
```ruby
foo(
bar, baz
)
```
```
> find bar
test.rb:3:2	bar
> find bar
test.rb:3:2	  bar, baz
```
Because parent node is on the previous line in the first case, so it displays only matched node. But the second case displays whole line.
I think the new behaviour is more natural than the current behaviour to me. And I can implement the new behaviour simpler.
=> Highlight matched expression in querly console

lib/querly/cli.rb
Querly exits with 0 currently when `querly.yaml` has syntax error.
For example:
```bash
$ cat querly.yaml
:
$ querly check
Failed to load configuration: querly.yaml
(<unknown>): did not find expected key while parsing a block mapping at line 1 column 1
Backtrace:
/home/pocke/.rbenv/versions/trunk/lib/ruby/2.6.0/psych.rb:402:in `parse'
/home/pocke/.rbenv/versions/trunk/lib/ruby/2.6.0/psych.rb:402:in `parse_stream'
/home/pocke/.rbenv/versions/trunk/lib/ruby/2.6.0/psych.rb:350:in `parse'
/home/pocke/.rbenv/versions/trunk/lib/ruby/2.6.0/psych.rb:263:in `load'
/home/pocke/.rbenv/versions/trunk/lib/ruby/gems/2.6.0/gems/querly-0.11.0/lib/querly/cli.rb:35:in `check'
/home/pocke/.rbenv/versions/trunk/lib/ruby/gems/2.6.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run' …
```
=> `exit 1` when `querly.yaml` has syntax error

lib/querly/cli/console.rb
Currently querly print an error and backtrace when parsing raises an error.
And I think the backtrace is not readable. It uses `p` method, so the backtrace shrinks to oneline.
This patch uses `puts` method instead of `p`. `puts` expands Array, so I think it is more readable.
before
```
$ querly console test.rb
Querly 0.11.0, interactive console
Commands:
- find PATTERN   Find PATTERN from given paths
- reload!        Reload program from paths
- quit
Loading...{:path=>#<Pathname:test.rb>, :script=>"#<Parser::SyntaxError: unexpected token tCOLON>"}
["/Users/pocke/.rbenv/versions/trunk/lib/ruby/gems/2.6.0/gems/parser-2.5.1.0/lib/parser/diagnostic/engine.rb:73:in `process'", "/Users/pocke/.rbenv/versions/trunk/lib/ruby/gems/2.6.0/gems/parser-2.5.1.0/lib/parser/base.rb:262:in `on_error'", …
```
=> Print readable backtrace

.gitignore, lib/querly/cli/console.rb
Resolve https://github.com/soutaro/querly/issues/46
Note that this is just an MVP; I think `history_file` and `history_size` should be configuable.
=> persistent history for `querly console`

lib/querly/cli.rb, lib/querly/cli/find.rb
`querly find $pattern [$path...]` is usable as a smart grep tool for Ruby, even if it is really slow for now.
What do you think of it?
=> Add subcommand `find pattern [paths]`

lib/querly/pattern/expr.rb, lib/querly/pattern/parser.y, test/pattern_parser_test.rb, test/pattern_test_test.rb
Proposed by @gfx in #52.
Currently, `...` pattern is allowed only if it does not have successive positional argument patterns. This patch allows `...` pattern anywhere positional argument pattern is allowed.
`foo(..., 1, ...)` is valid pattern now and works like the following:
```
foo(1)     # match
foo(1,2,3) # match
foo(0,1,2) # match
foo(2,3,4) # no match
```
=> Allow having `...` pattern in the middle of arguments

template.yml
See https://github.com/soutaro/querly/blob/v0.14.0/manual/configuration.md#check
```yaml
check:
- path: /test
rules:
- com.acme.corp
- append: com.acme.corp
- except: com.acme.corp
- only: com.acme.corp
- path: /test/unit
rules:
- append:
tags: foo bar
- except:
tags: foo bar
- only:
tags: foo bar
```
=> Fix config file generated by `querly init`

querly.gemspec
This allow to use `querly` with Rails 6.0 application.
I confirmed that tests pass with Active Support 6.0.beta1.
=> Relax Active Support version

lib/querly/cli/console.rb, test/cli/console_test.rb
I always type `exit` instead of `quit` 🙃
=> Exit the console with `exit`

manual/patterns.md
The documentation does not describe `as` syntax. This pull request adds an example of `as` syntax to the documentation.
=> Add documentation for `as` syntax

querly.gemspec
We cannot build racc v1.4.14 with Ruby trunk because of https://github.com/tenderlove/racc/pull/101 .
So I relaxed the racc dependency.
I introduced finxing version of rack in https://github.com/soutaro/querly/pull/1 .
I forget why I fixed it, but I think relaxed version is better :laughing: 
Thanks.
=> Relax racc dependency to fix build on Ruby trunk

lib/querly/pattern/parser.y, test/pattern_parser_test.rb, test/pattern_test_test.rb
Problem
===
`_` matcher with method chain raises a syntax error.
example
```yaml
rules:
- id: sample.abc
pattern:
- b._
message: a
examples:
- before: 'b.c'
after: 'b'
```
m
```console
$ querly test
/home/pocke/.rbenv/versions/trunk/lib/ruby/gems/2.7.0/gems/parser-2.6.2.0/lib/parser/lexer.rb:10861: warning: assigned but unused variable - testEof
/home/pocke/.rbenv/versions/trunk/lib/ruby/gems/2.7.0/gems/querly-0.15.1/lib/querly/node_pair.rb:28: warning: `&' interpreted as argument prefix
/home/pocke/.rbenv/versions/trunk/lib/ruby/gems/2.7.0/gems/querly-0.15.1/lib/querly/pattern/parser.rb:825: warning: mismatched indentations at 'end' with 'module' at 9
/home/pocke/.rbenv/versions/trunk/lib/ruby/gems/2.7.0/gems/querly-0.15.1/lib/querly/pattern/parser.rb:826: warning: mismatched …
```
=> Allow underscore for method name with receiver

lib/querly/pp/cli.rb
FYI
---
I tried `erubis -X` and `erb -x` but It doesn't work well in following example.
```erb
<%= content_tag :div do %>
bar
<% end %>
```
```
% erb -x foo.html.erb
#coding:ASCII-8BIT
_erbout = String.new; _erbout.concat(( content_tag :div do ).to_s); _erbout.concat "\n"
; _erbout.concat "  bar\n"
;  end ; _erbout.concat "\n"
; _erbout.force_encoding(__ENCODING__)
```
```
% erb -x foo.html.erb | ruby -c
-:2: syntax error, unexpected ')'
concat(( content_tag :div do ).to_s); _erbout.concat "\n"
^
-:4: syntax error, unexpected keyword_end, expecting ')'
;  end ; _erbout.concat "\n"
^
-:5: syntax error, unexpected end-of-input, expecting ')'
```
It has some noise.
```rb
path = "foo.html.erb"
erb = File.read(path)
template = ActionView::Template.new(erb, path, …
```
=> Add erb support

lib/querly/pattern/parser.y, manual/patterns.md, test/pattern_parser_test.rb
It will support string literal pattern.
e.g.
```yaml
pattern: 'require("active_support")'
```
It is useful for a shorthand of `:string: as 'name` and `where`. And we will be able to search with string literal in querly console by this feature.
Note: It will support really simple string. It means it does not the same as Ruby's one.
But I think it is enough for 95% cases. It should have more features, such as backslash escape, but it is enough for the first step.
Note 2: It only supports double quotation, because interpolation syntax already uses single quotation.
Note 3: Symbol literals is already supported! :tada:
https://github.com/pocke/querly/blob/21194401babfa918fa62160993db7111a478017e/lib/querly/pattern/parser.y#L152-L154
Goal
===
=> Support string literal in pattern

lib/querly/script.rb, lib/querly/script_enumerator.rb
Add a new class method `Querly::Script.load`.
Currently, Querly's Ruby parser depends on `Querly::ScriptEnumerator`. There are no problems in many cases, but it will be a concern when using Querly as a library (imagine call Querly's internal API from **another** Ruby application).
Because of this problem, it makes the parser dependent on the `Script`, not the `ScriptEnumerator`.
=> Add `Script.load`

lib/querly/cli.rb, lib/querly/cli/console.rb, lib/querly/cli/find.rb
Currenly `querly console` and `querly find` commands do not read the configuration file.
So they are not aware of the preprocessor config.
Querly does not look `.haml` files even if it's with the following configuration.
```yaml
preprocessor:
.haml: hamlit compile -
```
Pass config to console and find.
=> `console` and `find` with configuration file

lib/querly/pattern/expr.rb, test/pattern_test_test.rb
Close #70 
Querly will detect a method call with a safe navigation operator as a method call.
Currently Querly ignores safe navigation operator. So if we use `foo.bar` pattern, it only matches `foo.bar` Ruby code, but does not match `foo&.bar`.
This pull request will fix the problem.
I think it is useful. When I'd like to find all `foo` method call, it includes `x&.foo` also.
=> Detect safe navigation operator as a method call

.travis.yml
I've tested Querly with Ruby 2.7.1 on my local machine and there are no problems.
=> Add Ruby 2.7 and update supported Rubies

lib/querly/pattern/expr.rb, test/pattern_test_test.rb, test/test_helper.rb
I found `invalid byte sequence in UTF-8 error` error is raised with my source code.
If source contains byte sequence string literal like `"\xff"` and rule uses regexp like `/foo/`, the error raises.
This PR will fix it.
```yaml:querly.yml
rules:
- id: do_not_use_foo
pattern:
subject: ":string: as 'str"
where:
str: /foo/
message: Do not use foo.
```
```ruby:target.rb
"\xff"
```
=> Fix invalid bytes sequence in UTF-8 error

lib/querly/node_pair.rb, test/cli/console_test.rb, test/cli/test_test.rb, test/config_test.rb
https://github.com/soutaro/querly/runs/681068886?check_suite_focus=true#step:4:149
```
/__w/querly/querly/lib/querly/node_pair.rb:28: warning: `&' interpreted as argument prefix
/__w/querly/querly/test/cli/console_test.rb:64: warning: ambiguous first argument; put parentheses or a space even after `/' operator
/__w/querly/querly/test/cli/console_test.rb:69: warning: ambiguous first argument; put parentheses or a space even after `/' operator
/__w/querly/querly/test/cli/console_test.rb:74: warning: ambiguous first argument; put parentheses or a space even after `/' operator
/__w/querly/querly/test/cli/console_test.rb:79: warning: ambiguous first argument; put parentheses or a space even after `/' operator
/__w/querly/querly/test/cli/console_test.rb:84: warning: ambiguous first argument; …
```
=> Fix Ruby warnings

.github/workflows/ruby.yml
- Use [ruby/setup-ruby](https://github.com/ruby/setup-ruby) instead of `container_tag`.
- Split to each command on `steps`. This makes it clear which step fails.
- Update actions/checkout to v2.
=> Improve GitHub Actions workflow

.github/workflows/rubocop.yml, .rubocop.yml, Rakefile
This change aims to prevent unexpected Ruby warnings such as #80.
See also:
- https://github.com/rubocop-hq/rubocop-rubycw
- https://github.com/soutaro/querly/pull/80#issuecomment-653579050
- https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-error-message
=> Run rubocop-rubycw to prevent Ruby warnings

querly.gemspec
Rails 6.1.0 depends on Thor `"~> 1.0"`. So this fix is required to use Querly with Rails 6.1.0.
https://github.com/rails/rails/blob/8fd81f4980b76c4dbf0d0323482bc55e20bff308/railties/railties.gemspec#L43
By the way, Thor 1.0.0 doesn't have breaking changes. So we can upgrade
to Thor 1.0.0 without code changes.
https://github.com/erikhuda/thor/blob/master/CHANGELOG.md#100
=> Relax Thor version

lib/querly/pp/cli.rb
I found that `querly-pp erb` pre-process comments in *.erb wrongly.
```
$ cat foo.erb
<%# ] %>
$ querly-pp erb < foo.erb
] ;
```
`querly-pp erb` can output invalid syntax ruby codes.
This PR will fix it.
```
$ querly version
Querly 1.1.0
```
=> Fix erb comment preprocess

lib/querly/cli/formatter.rb, test/smoke_test.rb
When checking a big file, I sometimes have been hard to find where a syntax error occurs.
Perhaps, this change can help users find and report a problem such as #78 more easily.
Before:
```console
$ querly check foo.rb
Failed to load script: foo.rb
#<Parser::SyntaxError: unexpected token $end>
```
After:
```console
$ querly check foo.rb
Failed to load script: foo.rb
foo.rb:2:1: error: unexpected token $end
foo.rb:2:
foo.rb:2:
```
=> Show diagnostic info on syntax error

.github/workflows/ruby.yml
- Add Ruby 3.0 to the build matrix.
- Use `bundler-cache` for simplicity.
See <https://github.com/ruby/setup-ruby#matrix-of-ruby-versions>
=> Update CI configuration

.github/workflows/ruby.yml, lib/querly.rb, lib/querly/cli/test.rb, lib/querly/script.rb, querly.gemspec, test/data/test4/querly.yml, test/data/test4/script.rb, test/smoke_test.rb, test/test_helper.rb
This change aims to support newer Rubies 3.0 and 2.7.
Also, this requires Ruby 2.7 or newer (**breaking change**).
Close #78
=> Require Ruby 3.0 and 2.7
